package types

import (
        "cosmossdk.io/errors"
)

var (
        ErrUnauthorized               = errors.Register(ModuleName, 1, "unauthorized")
        ErrMintAuthorityNotFound      = errors.Register(ModuleName, 2, "mint authority not found")
        ErrBurnAuthorityNotFound      = errors.Register(ModuleName, 3, "burn authority not found")
        ErrAuthorityNotActive         = errors.Register(ModuleName, 4, "authority not active")
        ErrAuthorityExpired           = errors.Register(ModuleName, 5, "authority has expired")
        ErrDailyMintCapExceeded       = errors.Register(ModuleName, 6, "daily mint cap exceeded")
        ErrDailyBurnCapExceeded       = errors.Register(ModuleName, 7, "daily burn cap exceeded")
        ErrSingleMintLimitExceeded    = errors.Register(ModuleName, 8, "single mint limit exceeded")
        ErrSingleBurnLimitExceeded    = errors.Register(ModuleName, 9, "single burn limit exceeded")
        ErrTotalSupplyCapExceeded     = errors.Register(ModuleName, 10, "total supply cap exceeded")
        ErrWalletTypeNotAllowed       = errors.Register(ModuleName, 11, "wallet type not allowed for TSC operations")
        ErrJurisdictionNotAllowed     = errors.Register(ModuleName, 12, "jurisdiction not allowed")
        ErrPurposeNotAllowed          = errors.Register(ModuleName, 13, "purpose not allowed for this authority")
        ErrReasonNotAllowed           = errors.Register(ModuleName, 14, "reason not allowed for this authority")
        ErrInsufficientBalance        = errors.Register(ModuleName, 15, "insufficient TSC balance")
        ErrWalletNotFound             = errors.Register(ModuleName, 16, "wallet not found")
        ErrWalletNotActive            = errors.Register(ModuleName, 17, "wallet not active")
        ErrComplianceCheckFailed      = errors.Register(ModuleName, 18, "compliance check failed")
        ErrInvalidAmount              = errors.Register(ModuleName, 19, "invalid amount")
        ErrInvalidParams              = errors.Register(ModuleName, 20, "invalid parameters")
        ErrAuthorityAlreadyExists     = errors.Register(ModuleName, 21, "authority already exists")
        ErrOperationNotFound          = errors.Register(ModuleName, 22, "operation not found")
        ErrOperationAlreadyCompleted  = errors.Register(ModuleName, 23, "operation already completed")
        ErrKycTierInsufficient        = errors.Register(ModuleName, 24, "KYC tier insufficient")
        ErrTravelRuleRequired         = errors.Register(ModuleName, 25, "travel rule data required")
        ErrIdentityNotFound           = errors.Register(ModuleName, 26, "identity not found")
        ErrIdentityNotActive          = errors.Register(ModuleName, 27, "identity not active")
        ErrMintDisabled               = errors.Register(ModuleName, 28, "minting is currently disabled")
        ErrBurnDisabled               = errors.Register(ModuleName, 29, "burning is currently disabled")
        ErrTransferDisabled           = errors.Register(ModuleName, 30, "transfers are currently disabled")
        ErrInsufficientSupply         = errors.Register(ModuleName, 31, "burn amount exceeds total supply")

        ErrProofIdEmpty               = errors.Register(ModuleName, 100, "proof_id cannot be empty")
        ErrProofVersionEmpty          = errors.Register(ModuleName, 101, "proof_version cannot be empty")
        ErrPolicyHashEmpty            = errors.Register(ModuleName, 102, "policy_hash cannot be empty")
        ErrRequestIdEmpty             = errors.Register(ModuleName, 103, "request_id cannot be empty")
        ErrNonceEmpty                 = errors.Register(ModuleName, 104, "nonce cannot be empty")
        ErrTimestampInvalid           = errors.Register(ModuleName, 105, "timestamp must be positive")
        ErrOperationTypeEmpty         = errors.Register(ModuleName, 106, "operation_type cannot be empty")
        ErrProofExpired               = errors.Register(ModuleName, 107, "commit proof has expired")
        ErrPolicyNotActive            = errors.Register(ModuleName, 108, "policy is not active")
        ErrPolicyHashMismatch         = errors.Register(ModuleName, 109, "policy hash does not match active policy")
        ErrInsufficientApprovals      = errors.Register(ModuleName, 110, "insufficient approvals for operation")
        ErrApprovalThresholdNotMet    = errors.Register(ModuleName, 111, "approval threshold not met for required role")
        ErrCustodyAttestationRequired = errors.Register(ModuleName, 112, "custody attestation required but missing")
        ErrCustodyAttestationInvalid  = errors.Register(ModuleName, 113, "custody attestation signature invalid")
        ErrCustodyAttestationExpired  = errors.Register(ModuleName, 114, "custody attestation has expired")
        ErrComplianceAttestationRequired = errors.Register(ModuleName, 115, "compliance attestation required but missing")
        ErrComplianceAttestationInvalid  = errors.Register(ModuleName, 116, "compliance attestation signature invalid")
        ErrComplianceAttestationExpired  = errors.Register(ModuleName, 117, "compliance attestation has expired")
        ErrComplianceCheckNotPassed   = errors.Register(ModuleName, 118, "compliance check did not pass")
        ErrNonceAlreadyUsed           = errors.Register(ModuleName, 119, "nonce/request_id already used (replay detected)")
        ErrOperationNotAllowed        = errors.Register(ModuleName, 120, "operation type not allowed by policy")
        ErrCorridorNotAllowed         = errors.Register(ModuleName, 121, "corridor not allowed by policy")
        ErrAmountExceedsLimit         = errors.Register(ModuleName, 122, "amount exceeds policy limit")
        ErrQuoteOutOfBounds           = errors.Register(ModuleName, 123, "quote price outside allowed bounds")
        ErrApprovalExpired            = errors.Register(ModuleName, 124, "one or more approvals have expired")
        ErrApprovalSignatureInvalid   = errors.Register(ModuleName, 125, "approval signature verification failed")
        ErrProofNotFound              = errors.Register(ModuleName, 126, "commit proof not found")
        ErrInvariantViolation         = errors.Register(ModuleName, 127, "invariant violation detected")
        ErrObligationNotFound         = errors.Register(ModuleName, 128, "obligation not found")
        ErrObligationAlreadyFinalized = errors.Register(ModuleName, 129, "obligation already finalized")
        ErrObligationNotReady         = errors.Register(ModuleName, 130, "obligation not ready for finalization")
)
